camera0: 0
camera1: 1
frame_width: 1640
frame_height: 1232
mono_calibration_frames: 10
stereo_calibration_frames: 10
view_resize: 1
checkerboard_box_size_scale : 2.50
checkerboard_rows: 6
checkerboard_columns: 8
cooldown: 100
